name: Build and push images

on: 
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build and push images
    # if: ${{ github.ref == 'refs/heads/main' }}
    strategy:
      matrix:
        page: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
        page-total: [11]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - name: Free more space
      id: free_space 
      run: |
        set -e
        # Ensure enough space is available for build
        sudo apt-get autoremove -y
        sudo apt-get clean -y
        sudo rm -rf /usr/share/dotnet

  image-info:
    name: Trigger info extraction
    needs: [build-and-push]
    uses: devcontainers/images/.github/workflows/version-history.yml@samruddhikhandale/push-test
      with:
        release: "refs/tags/v0.0.1"
        cg: "false"
        push: "true"
        overwrite: "false"
      secrets: inherit
